agregando cambios al cuerpo
expertic-heisohn/piano pull request #1
Opened 2019-10-30 20:17 UTC by juanthe7

Creación de las teclas del piano- cuerpo y teclas

2019-10-30 20:27 UTC, sneider1994 approved these changes
Eres Genial

2019-10-30 20:37 UTC, Jhontejada13 requested changes
cambios aprobados

2019-10-30 20:37 UTC, Jhontejada13 commented on piano.html
> -
Por favor quitar esta línea

2019-10-31 01:57 UTC, juliangranda requested changes
esto es una prueba

2019-10-31 01:58 UTC, juliangranda commented
.

2019-10-31 01:58 UTC, juliangranda commented
> .

2019-10-31 03:39 UTC, Jhontejada13 approved these changes
Cambios aprobados,

2019-10-31 19:13 UTC, closed without merging